version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: /docker/php/Dockerfile
    container_name: laravel-app
    ports:
      - "300:8000"
    volumes:
      - ./juicio:/var/www
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

