version: "3.7"
services:

    webserver:
      image: nginx
      container_name: webserver
      working_dir: /gatewayJuridico
      volumes:
          - ./gatewayJuridico:/gatewayJuridico
          - ./docker/nginx:/etc/nginx/conf.d
      ports:
       - "260:260"
      networks:
        - ipam

    php-fpm:
      build: docker/php
      container_name: phpfpm
      working_dir: /gatewayJuridico
      volumes:
        - ./gatewayJuridico:/gatewayJuridico
      networks:
        - ipam
networks:
    ipam:
        driver: bridge